repos:
  # ## general
  # - repo: git://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.0.1
  #   hooks:
  #     # Common errors
  #     - id: end-of-file-fixer
  #       exclude_types: [sql]
  #     - id: trailing-whitespace
  #       args: [--markdown-linebreak-ext=md]
  #       exclude_types: [sql]
  #     - id: check-yaml
  #     - id: check-executables-have-shebangs
  #     # Cross platform
  #     - id: check-case-conflict
  #     - id: mixed-line-ending
  #       args: [--fix=lf]
  #       exclude_types: [sql]
  #     # Security
  #     - id: detect-aws-credentials
  #       args: ['--allow-missing-credentials']
  #     - id: detect-private-key
  ## terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tfsec
        args:
          - --args=--exclude-downloaded-modules
      - id: terraform_validate
