--
-- Roles
--

CREATE ROLE "PARTY_USER";
ALTER ROLE "PARTY_USER" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
GRANT "PARTY_USER" TO "${flywayUser}";
ALTER USER "PARTY_USER" WITH PASSWORD '${partyUserPassword}';

CREATE ROLE "MONITORING_USER";
ALTER ROLE "MONITORING_USER" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
ALTER USER "MONITORING_USER" WITH PASSWORD '${monitoringUserPassword}';

CREATE ROLE "MONITORING_EXTERNAL_USER";
ALTER ROLE "MONITORING_EXTERNAL_USER" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
ALTER USER "MONITORING_EXTERNAL_USER" WITH PASSWORD '${monitoringExternalUserPassword}';

-- Database privileges
--

GRANT CONNECT ON DATABASE selc TO "PARTY_USER";
GRANT CONNECT ON DATABASE selc TO "MONITORING_USER";
GRANT CONNECT ON DATABASE selc TO "MONITORING_EXTERNAL_USER";

-- schema creation
--

CREATE SCHEMA party;
ALTER SCHEMA party OWNER TO "PARTY_USER";

-- schema grants
--

ALTER DEFAULT PRIVILEGES IN SCHEMA party GRANT ALL PRIVILEGES ON TABLES TO "PARTY_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA party GRANT USAGE ON SEQUENCES TO "PARTY_USER";

GRANT USAGE ON SCHEMA party TO "MONITORING_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "MONITORING_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA party GRANT SELECT ON TABLES TO "MONITORING_USER";

GRANT USAGE ON SCHEMA party TO "MONITORING_EXTERNAL_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "MONITORING_EXTERNAL_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA party GRANT SELECT ON TABLES TO "MONITORING_EXTERNAL_USER";