--
-- Roles
--

CREATE ROLE "SELC_USER";
ALTER ROLE "SELC_USER" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
ALTER USER "SELC_USER" WITH PASSWORD '${selcUserPassword}';

CREATE ROLE "MONITORING_USER";
ALTER ROLE "MONITORING_USER" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
ALTER USER "MONITORING_USER" WITH PASSWORD '${monitoringUserPassword}';

CREATE ROLE "MONITORING_EXTERNAL_USER";
ALTER ROLE "MONITORING_EXTERNAL_USER" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
ALTER USER "MONITORING_EXTERNAL_USER" WITH PASSWORD '${monitoringExternalUserPassword}';

-- Database creation
--

GRANT ALL ON DATABASE selc TO "SELC_USER";
GRANT CONNECT ON DATABASE selc TO "MONITORING_USER";
GRANT CONNECT ON DATABASE selc TO "MONITORING_EXTERNAL_USER";

-- schema grants
--

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO "SELC_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO "SELC_USER";

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "MONITORING_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "MONITORING_EXTERNAL_USER";
