--
-- Roles
--

CREATE ROLE "MOCK_REGISTRY_USER";
ALTER ROLE "MOCK_REGISTRY_USER" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
GRANT "MOCK_REGISTRY_USER" TO "${flywayUser}";
ALTER USER "MOCK_REGISTRY_USER" WITH PASSWORD '${mockRegistryUserPassword}';

-- Database privileges
--

GRANT CONNECT ON DATABASE selc TO "MOCK_REGISTRY_USER";

-- schema creation
--

CREATE SCHEMA mock_registry;
ALTER SCHEMA mock_registry OWNER TO "MOCK_REGISTRY_USER";

-- schema grants
--

ALTER DEFAULT PRIVILEGES IN SCHEMA mock_registry GRANT ALL PRIVILEGES ON TABLES TO "MOCK_REGISTRY_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA mock_registry GRANT USAGE ON SEQUENCES TO "MOCK_REGISTRY_USER";

GRANT USAGE ON SCHEMA mock_registry TO "MONITORING_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "MONITORING_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA mock_registry GRANT SELECT ON TABLES TO "MONITORING_USER";

GRANT USAGE ON SCHEMA mock_registry TO "MONITORING_EXTERNAL_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "MONITORING_EXTERNAL_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA mock_registry GRANT SELECT ON TABLES TO "MONITORING_EXTERNAL_USER";