name: Core Code Review

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - src/core/**
      - .github/workflows/code_review.yml
      - .github/workflows/call_review.yml

  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - dev
          - uat
          - prod

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  plan:
    uses: ./.github/workflows/call_review.yml
    name: Core Code Review
    secrets: inherit
    with:
      environment: dev
      dir: "./src/core"
      agent: ubuntu-latest
